### ISSUE TITLE
copy instead of move?

### ISSUE THREAD

**Issue by Lewiscowles1986** [RPi-Distro/raspberrypi-net-mods#1]
Would it not be easier to simply copy from `/boot/.root/etc/wpa_supplicant/wpa_supplicant.conf` if it exists once at boot? (the `/boot/wpa_supplicant.conf` currently goes away after it's copied, which I feel could confuse users)

**Agenda**
I'm thinking of a larger set of customization ability for the pi. Currently at each boot I copy the entire contents of `/boot/.root` over `/`. Whilst I realize my own method needs work, perhaps there is a middle-ground to enable easier customization of the pi for non-snappy core applications or config?

**Comment by XECDesign** [comment]
The reason for moving is to give some feedback that it worked and to avoid leaving cruft behind. I do not believe copying arbitrary files from the boot partition is in general a good way to customise the install.

**Comment by Lewiscowles1986** [comment]
Sorry, this is taking files from the boot partition already, so I'm not sure I can get my head around.

> I do not believe copying arbitrary files from the boot partition is in general a good way to customise the install.

Surely an artifact of the move for the existing script is a working wireless connection? the difference is I cannot check if the two files are identical (for updating an existing working file) from the running distro after the file has been moved. This is more a concern for already connected pi's.

I accept we have a difference of opinion, I'd just like to understand where you are coming from.

**Comment by XECDesign** [comment]
Copying all files is not great, since FAT32 doesn't support permissions and arguably, it just makes it much easier to spread malware. It's just not an elegant solution.

Currently, it's taking a single file that was frequently requested, just because the trade off is worth it. It wasn't intended as a gateway for general customisation.

**Comment by Lewiscowles1986** [comment]
I see. Thanks, I can always put a mounted loop image on the device for permissions, I don't have to share it :wink:
