### ISSUE TITLE
"rfkill: cannot open /dev/rfkill: Permission denied" when NetworkManager service is disabled.

### ISSUE THREAD

**Issue by heraclitusq** [RPi-Distro/raspberrypi-net-mods#12]
The message `rfkill: cannot open /dev/rfkill: Permission denied` pops up each time when I log into the rpi via ssh.

This is a headless rpi2 with Bookworm lite installed. Since it has no wifi/bt and the network environment is pretty stable, the NetworkManager service was disabled and the network was configured via /etc/network/interface.

A bit research shows that the permission of /dev/rfkill on this rpi2 is:
`crw------- 1 root root /dev/rfkill`
The same permission is observed from a minimal installed debian12 (without any NetworkManager/dhcpcd service)

When the NetworkManager serivce was enabled, the permission was changed (presumably by the NetworkManager) to:
`crw-rw-r-- 1 root netdev /dev/rfkill`
And the permission denied message went away.

It seems that an if condition could be added into the `wifi-checker.sh` to check if /dev/rfkill is readable, in order to accommodate this scenario, something like:
```shell
if [ ! -r /dev/rfkill ]; then
    exit 0
fi
```
after checking the existence of /usr/sbin/rfkill and /dev/rfkill.

**Comment by XECDesign** [comment]
Hmm. rfkill's permissions are set up /lib/udev/rules.d/80-ifupdown.rules, which ships with the ifupdown package. I'm not sure why yours would have the wrong permissions, given that you're using ifupdown.
