### ISSUE TITLE
Version 1.3.1 causes 90 second delay in eth0 bringup

### ISSUE THREAD

**Issue by pdball** [RPi-Distro/raspberrypi-net-mods#6]
I have this in config.txt
dtoverlay=disable-wifi
dmesg output:
[    8.545604] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
[   93.320477] 8021q: 802.1Q VLAN Support v1.8
[   93.394206] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   93.418791] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   93.488374] bcmgenet fd580000.ethernet: configuring instance for external RGMII (RX delay)
[   93.488656] bcmgenet fd580000.ethernet eth0: Link is Down
[   95.302414] broken atomic modeset userspace detected, disabling atomic
[   97.630216] fuse: init (API version 7.32)
[   97.678064] bcmgenet fd580000.ethernet eth0: Link is Up - 1Gbps/Full - flow control rx/tx
[   97.678144] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   99.783671] EXT4-fs (sda): mounted filesystem with ordered data mode. Opts: (null)

**Comment by pdball** [comment]
And boot.log has this:
[ TIME ] Timed out waiting for device /sys/devices/virtual/misc/rfkill.
[DEPEND] Dependency failed for Load/Save RF Kill Switch Status.

**Comment by XECDesign** [comment]
Thanks, I see how that could happen. I have reverted the commit until a better solution is found.

**Comment by XhmikosR** [comment]
This was driving me crazy and I couldn't pinpoint the root cause. I mean, I did see the delay in `8021q: 802.1Q VLAN` step, but I had no idea what was causing it.

Glad it was sorted, now booting is back to ~15 seconds for a headless system :)

**Comment by un99known99** [comment]
Hi, what exactly was the issue and what was reverted back? My log2ram is failing at start:
ExecStart=/usr/local/bin/log2ram start (code=killed, signal=TERM) - need urgent help :) driving me crazy, could manually start it afterwards via sudo systemctl restart log2ram.
Thx, br, Mike

**Comment by un99known99** [comment]
log2ram.service - Log2Ram
   Loaded: loaded (/etc/systemd/system/log2ram.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Sat 2022-01-01 09:57:54 CET; 1min 18s ago
  Process: 280 ExecStart=/usr/local/bin/log2ram start (code=killed, signal=TERM)
 Main PID: 280 (code=killed, signal=TERM)

**Comment by XECDesign** [comment]
Sorry, looks like somebody (me) forgot to `git push`.

https://github.com/RPi-Distro/raspberrypi-net-mods/commit/c26bbc6baaea5c07180a05a1427cc160b57b8567

`systemd-rfkill.service` doesn't run if there are no wifi devices, so I believe that that line was causing a timeout.
