### ISSUE TITLE
Remove dhcpcd5 dependency

### ISSUE THREAD

**Issue by Taha-Firoz** [RPi-Distro/raspberrypi-net-mods#9]
The mod works with wpa_supplicant not dhcpd5 I don't understand why is that a dependency. I've setup a build that uses network manager and I have to specifically remove this package when building the image or else it pulls in dhcpcd5 even though it's not needed but that also removes my ability to load a network configuration before boot.

**Comment by XECDesign** [comment]
Raspberry Pi OS is intended to work with dhcpcd. If you're doing something else, it makes sense to remove this package and find other ways around the features we offer.

Without dhcpcd, this package doesn't make sense.

On the bright side, NM will also be supported in the near future.

**Comment by Taha-Firoz** [comment]
Doesn't this package just work with wpa_supplicant or does it interact with dhcpd5 directly too?

**Comment by XECDesign** [comment]
dhcpcd is what runs wpa_supplicant in a way that uses wpa_supplicant.conf. Everything else on the system assumes we're using dhcpcd as well. Even if this package had nothing to do with dhcpcd, we'd still have it install dhcpcd.

**Comment by Taha-Firoz** [comment]
> On the bright side, NM will also be supported in the near future.

Do you mean nm will be supported by this package or will it be supported by raspberry-pi os. Ubuntu for raspberry pi already uses nm

**Comment by XECDesign** [comment]
> Do you mean nm will be supported by this package or will it be supported by raspberry-pi os.

Both

> Ubuntu for raspberry pi already uses nm

Are you running Ubuntu?

**Comment by Taha-Firoz** [comment]
No I've built my own rpios image with pi-gen it was pretty straightforward but when I swapped dhcpd for nm I still had dhcpd in my image and it took me a while to figure out which package was pulling it back in 😅
